services:
 api:
   restart: always
   build: .
   environment:
     PORT: 80
     DEBUG: false
     JWT_SECRET_KEY: <SECRET KEY>
     DATABASE_URL: mysql+pymysql://database:3306/db?user=root&password=root
   ports:
    - 80:80
   networks:
     - app
 database:
   image: mysql
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD=root
   volumes:
     - ./.mysql/data:/var/lib/mysql
   networks:
     - app
networks:
  app:
    driver: bridge